version: '3'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bee run --downdoc=true --gendoc=true
    volumes:
      - .:/go/src/DNAChainChallenge
    working_dir: /go/src/DNAChainChallenge
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db