version: '3'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bee run --downdoc=true --gendoc=true
    volumes:
      - .:/go/src/DNAChainChallenge
    working_dir: /go/src/DNAChainChallenge
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      DB_HOST: db:5432
    depends_on:
      - db