name: dna-challenge CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'dna-chain-app' }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Compose build
      - name: Compose build
        run: docker-compose build web

      # Build Docker image
      - name: Docker login
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Run migrations
        run: heroku run bee migrate --conn=$DATABASE_URL --driver="postgres" -a $APP_NAME